/*
* generated by Xtext
*/
package org.xtext.example.mydsl.ui.contentassist;

import org.eclipse.emf.ecore.EObject;
import org.eclipse.xtext.RuleCall;
import org.eclipse.xtext.ui.editor.contentassist.ContentAssistContext;
import org.eclipse.xtext.ui.editor.contentassist.ICompletionProposalAcceptor;
import org.xtext.example.mydsl.ui.contentassist.AbstractInsuranceProposalProvider;
/**
 * see http://www.eclipse.org/Xtext/documentation/latest/xtext.html#contentAssist on how to customize content assistant
 */
public class InsuranceProposalProvider extends AbstractInsuranceProposalProvider {

	@Override
	public void complete_YesNo(EObject model, RuleCall ruleCall,
			ContentAssistContext context, ICompletionProposalAcceptor acceptor) {
		acceptor.accept(createCompletionProposal("TAK", context));
		acceptor.accept(createCompletionProposal("NIE", context));
		super.complete_YesNo(model, ruleCall, context, acceptor);
	}

}
