/*
 * generated by Xtext
 */
package org.xtext.example.mydsl.ui;

import org.eclipse.xtext.ui.guice.AbstractGuiceAwareExecutableExtensionFactory;
import org.osgi.framework.Bundle;

import com.google.inject.Injector;

import org.xtext.example.mydsl.ui.internal.InsuranceActivator;

/**
 * This class was generated. Customizations should only happen in a newly
 * introduced subclass. 
 */
public class InsuranceExecutableExtensionFactory extends AbstractGuiceAwareExecutableExtensionFactory {

	@Override
	protected Bundle getBundle() {
		return InsuranceActivator.getInstance().getBundle();
	}
	
	@Override
	protected Injector getInjector() {
		return InsuranceActivator.getInstance().getInjector(InsuranceActivator.ORG_XTEXT_EXAMPLE_MYDSL_INSURANCE);
	}
	
}
