/*
* generated by Xtext
*/
package org.xtext.example.mydsl.ui.contentassist.antlr;

import java.util.Collection;
import java.util.Map;
import java.util.HashMap;

import org.antlr.runtime.RecognitionException;
import org.eclipse.xtext.AbstractElement;
import org.eclipse.xtext.ui.editor.contentassist.antlr.AbstractContentAssistParser;
import org.eclipse.xtext.ui.editor.contentassist.antlr.FollowElement;
import org.eclipse.xtext.ui.editor.contentassist.antlr.internal.AbstractInternalContentAssistParser;

import com.google.inject.Inject;

import org.xtext.example.mydsl.services.InsuranceGrammarAccess;

public class InsuranceParser extends AbstractContentAssistParser {
	
	@Inject
	private InsuranceGrammarAccess grammarAccess;
	
	private Map<AbstractElement, String> nameMappings;
	
	@Override
	protected org.xtext.example.mydsl.ui.contentassist.antlr.internal.InternalInsuranceParser createParser() {
		org.xtext.example.mydsl.ui.contentassist.antlr.internal.InternalInsuranceParser result = new org.xtext.example.mydsl.ui.contentassist.antlr.internal.InternalInsuranceParser(null);
		result.setGrammarAccess(grammarAccess);
		return result;
	}
	
	@Override
	protected String getRuleName(AbstractElement element) {
		if (nameMappings == null) {
			nameMappings = new HashMap<AbstractElement, String>() {
				private static final long serialVersionUID = 1L;
				{
					put(grammarAccess.getYesNoAccess().getAlternatives(), "rule__YesNo__Alternatives");
					put(grammarAccess.getProductAccess().getGroup(), "rule__Product__Group__0");
					put(grammarAccess.getProductAccess().getGroup_15(), "rule__Product__Group_15__0");
					put(grammarAccess.getModelAccess().getProductsAssignment(), "rule__Model__ProductsAssignment");
					put(grammarAccess.getProductAccess().getNameAssignment_1(), "rule__Product__NameAssignment_1");
					put(grammarAccess.getProductAccess().getDescriptionAssignment_4(), "rule__Product__DescriptionAssignment_4");
					put(grammarAccess.getProductAccess().getAvgDamagesAssignment_6(), "rule__Product__AvgDamagesAssignment_6");
					put(grammarAccess.getProductAccess().getOccurrencesAssignment_8(), "rule__Product__OccurrencesAssignment_8");
					put(grammarAccess.getProductAccess().getEarningsAssignment_10(), "rule__Product__EarningsAssignment_10");
					put(grammarAccess.getProductAccess().getCostAssignment_12(), "rule__Product__CostAssignment_12");
					put(grammarAccess.getProductAccess().getSellingAssignment_14(), "rule__Product__SellingAssignment_14");
					put(grammarAccess.getProductAccess().getConnectedAssignment_15_1(), "rule__Product__ConnectedAssignment_15_1");
				}
			};
		}
		return nameMappings.get(element);
	}
	
	@Override
	protected Collection<FollowElement> getFollowElements(AbstractInternalContentAssistParser parser) {
		try {
			org.xtext.example.mydsl.ui.contentassist.antlr.internal.InternalInsuranceParser typedParser = (org.xtext.example.mydsl.ui.contentassist.antlr.internal.InternalInsuranceParser) parser;
			typedParser.entryRuleModel();
			return typedParser.getFollowElements();
		} catch(RecognitionException ex) {
			throw new RuntimeException(ex);
		}		
	}
	
	@Override
	protected String[] getInitialHiddenTokens() {
		return new String[] { "RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT" };
	}
	
	public InsuranceGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}
	
	public void setGrammarAccess(InsuranceGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
}
